INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Model T", "Luxuoso", "Hatch", "preto", "imperdiet.nec@Donecestmauris.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Imperial", "Confortavel", "Perua/Van", "amarelo", "et.malesuada@magnaCrasconvallis.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("2CV", "Luxuoso", "Perua/Van", "vermelho", "consequat@egestasa.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Minx Magnificent", "Confortavel", "Perua/Van", "amarelo", "fermentum@gravida.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Corvette", "Confortavel", "Hatch", "branco", "Donec.luctus@velsapienimperdiet.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Fleetwood", "Confortavel", "Hatch", "vermelho", "faucibus.ut@intempus.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Thunderbird", "Luxuoso", "Perua/Van", "verde", "dapibus.id.blandit@temporest.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("600", "Luxuoso", "Hatch", "prata", "fringilla.euismod.enim@litoratorquentper.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mini", "Basico", "Perua/Van", "prata", "nec.mollis@enimgravidasit.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Corvair", "Luxuoso", "Sedan", "branco", "facilisis.Suspendisse.commodo@sempertellusid.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Fillmore", "Basico", "SUV", "preto", "Pellentesque.habitant.morbi@sodales.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Rockette", "Basico", "Hatch", "prata", "dolor.dapibus@nibhlaciniaorci.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mini Cooper", "Luxuoso", "Hatch", "vermelho", "feugiat.nec.diam@tincidunt.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Avanti", "Confortavel", "Perua/Van", "amarelo", "at.auctor.ullamcorper@eu.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Tempest", "Basico", "SUV", "prata", "ante.Nunc.mauris@Nullafacilisis.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Grand Prix", "Confortavel", "Hatch", "azul", "dignissim@Donec.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Special", "Luxuoso", "SUV", "preto", "Nullam@semegestasblandit.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mini Cooper S", "Confortavel", "Hatch", "preto", "Praesent.eu@Nunc.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("E-Series", "Basico", "SUV", "azul", "tellus.justo@placerat.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Corvair 500", "Basico", "SUV", "vermelho", "varius.et@egestasSed.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mustang", "Basico", "Sedan", "branco", "lacinia.orci@aliquetmolestie.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Galaxie", "Luxuoso", "Sedan", "branco", "facilisis@malesuadaaugueut.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("LeMans", "Basico", "Sedan", "prata", "dui.in.sodales@vel.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Bonneville", "Basico", "Perua/Van", "prata", "nibh.Phasellus@sitamet.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Fairlane", "Confortavel", "Sedan", "amarelo", "mauris@rutrum.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Beetle", "Confortavel", "SUV", "amarelo", "Donec.fringilla@ridiculusmusProin.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Falcon", "Basico", "SUV", "branco", "pede@at.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Interceptor", "Confortavel", "Hatch", "verde", "Mauris@Inmi.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Toronado", "Luxuoso", "Sedan", "preto", "nisi.nibh@famesacturpis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Firebird", "Confortavel", "SUV", "azul", "posuere.enim@lectusjusto.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Camaro", "Luxuoso", "Sedan", "verde", "amet.consectetuer@ultricesDuisvolutpat.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Bel Air", "Basico", "Sedan", "verde", "lacus@pellentesqueafacilisis.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Country", "Luxuoso", "Sedan", "vermelho", "erat.semper@consequat.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Cougar", "Basico", "Hatch", "vermelho", "Class.aptent.taciti@acmetus.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Charger", "Basico", "Sedan", "branco", "lorem.sit@Cum.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("GT350", "Confortavel", "Perua/Van", "verde", "Nullam@accumsansedfacilisis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Torino", "Basico", "Sedan", "preto", "posuere.cubilia.Curae@arcu.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("914", "Basico", "Hatch", "branco", "lacinia.mattis@per.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Vega", "Basico", "Hatch", "verde", "lacinia.mattis.Integer@natoque.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("SM", "Confortavel", "SUV", "prata", "malesuada@cursusluctus.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Monte Carlo", "Basico", "Hatch", "preto", "pharetra.nibh.Aliquam@nequesed.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("CX", "Luxuoso", "Sedan", "amarelo", "ac.eleifend@Nulla.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Monza", "Basico", "Sedan", "prata", "ultrices.Duis@idante.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Golf", "Basico", "Perua/Van", "azul", "accumsan@lectus.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Celica", "Confortavel", "Sedan", "branco", "augue.eu@penatibus.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Caprice", "Luxuoso", "Perua/Van", "prata", "sit.amet.orci@quisaccumsanconvallis.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("W123", "Basico", "Perua/Van", "vermelho", "feugiat.non@tellus.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("MGB", "Basico", "SUV", "branco", "nunc.sit.amet@tortor.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Omni", "Basico", "Sedan", "amarelo", "sit.amet@Donectincidunt.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("280ZX", "Basico", "SUV", "verde", "egestas.a.dui@ipsumcursusvestibulum.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("LUV", "Luxuoso", "Perua/Van", "amarelo", "Etiam.gravida.molestie@aliquam.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Riviera", "Confortavel", "Sedan", "amarelo", "odio@risus.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Citation", "Basico", "Perua/Van", "vermelho", "Fusce.feugiat.Lorem@Nullam.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Civic", "Confortavel", "SUV", "preto", "Phasellus.dolor.elit@auctor.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Aries", "Confortavel", "Hatch", "preto", "neque.tellus.imperdiet@massaIntegervitae.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("W126", "Luxuoso", "Sedan", "branco", "porttitor@libero.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("6000", "Luxuoso", "SUV", "branco", "dictum.ultricies@turpisNulla.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Sunbird", "Luxuoso", "Perua/Van", "prata", "ornare@lorem.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Accord", "Confortavel", "Sedan", "prata", "pharetra@neque.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Alliance", "Basico", "Hatch", "vermelho", "lorem.ac@nullaante.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("626", "Luxuoso", "Sedan", "amarelo", "Nam@fermentummetusAenean.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("RX-7", "Confortavel", "SUV", "amarelo", "In.tincidunt.congue@id.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("944", "Basico", "SUV", "vermelho", "ornare.sagittis.felis@loremipsum.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("1000", "Luxuoso", "Sedan", "branco", "placerat.Cras@semmagnanec.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Parisienne", "Basico", "Hatch", "prata", "Quisque.libero.lacus@vitaeorci.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Fiero", "Luxuoso", "SUV", "azul", "vitae.purus@massarutrum.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Firefly", "Basico", "Perua/Van", "preto", "Fusce.diam.nunc@mollis.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Bronco II", "Luxuoso", "Perua/Van", "verde", "nunc.ullamcorper.eu@scelerisquenequesed.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Laser", "Basico", "SUV", "amarelo", "dui.in@lobortis.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("EXP", "Confortavel", "Hatch", "vermelho", "sit@Aenean.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Ranger", "Confortavel", "Perua/Van", "amarelo", "dui.nec.tempus@Integer.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Escort", "Luxuoso", "SUV", "amarelo", "tincidunt.nibh@felis.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Tempo", "Confortavel", "Sedan", "amarelo", "dictum@anteNuncmauris.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("LTD", "Luxuoso", "SUV", "amarelo", "Fusce.diam@risusNunc.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("F250", "Luxuoso", "SUV", "preto", "Duis.ac.arcu@velvulputate.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("F150", "Luxuoso", "Perua/Van", "azul", "metus@idenim.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("E250", "Confortavel", "Sedan", "vermelho", "habitant@ametconsectetueradipiscing.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("LTD Crown Victoria", "Luxuoso", "Perua/Van", "branco", "a.nunc@parturient.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Bronco", "Basico", "Sedan", "verde", "In.at@parturient.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("E150", "Luxuoso", "SUV", "prata", "pellentesque.massa@pharetraut.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Galant", "Confortavel", "Hatch", "vermelho", "Quisque@libero.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mirage", "Basico", "SUV", "prata", "ac@nisl.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Starion", "Luxuoso", "SUV", "vermelho", "et@asollicitudinorci.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Pajero", "Luxuoso", "Hatch", "verde", "ac@placeratvelitQuisque.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Cordia", "Basico", "Hatch", "preto", "quam.Pellentesque.habitant@aliquet.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Tredia", "Luxuoso", "Hatch", "azul", "dignissim.magna@SednequeSed.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Brat", "Luxuoso", "Sedan", "branco", "Nunc.mauris@enimSuspendisse.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("S-Class", "Luxuoso", "Perua/Van", "azul", "sed.facilisis.vitae@quamCurabiturvel.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("E-Class", "Confortavel", "Perua/Van", "verde", "erat.Vivamus@MaurisnullaInteger.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("W201", "Confortavel", "Hatch", "branco", "Duis.elementum@lectusrutrumurna.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("SL-Class", "Confortavel", "SUV", "branco", "tincidunt.adipiscing.Mauris@feugiatmetus.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Topaz", "Confortavel", "Perua/Van", "branco", "Donec.tincidunt@egetmetusIn.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Grand Marquis", "Confortavel", "Hatch", "branco", "hendrerit.Donec.porttitor@molestiesodales.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Lynx", "Luxuoso", "Sedan", "branco", "enim.gravida.sit@convallisconvallisdolor.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Capri", "Luxuoso", "Sedan", "preto", "Duis.mi@loremvitae.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Marquis", "Confortavel", "Hatch", "prata", "et.rutrum.non@quam.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Esprit Turbo", "Luxuoso", "Sedan", "verde", "nisi@Vivamusnon.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Jetta", "Luxuoso", "Sedan", "prata", "auctor.velit@ornareelitelit.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Vanagon", "Basico", "Hatch", "amarelo", "ad.litora@Nullamvelit.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Scirocco", "Confortavel", "Hatch", "verde", "eget.metus.In@acorci.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Quantum", "Confortavel", "Sedan", "verde", "lorem.eu@auctor.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Electra", "Confortavel", "Perua/Van", "branco", "sit.amet@arcu.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Century", "Confortavel", "Perua/Van", "amarelo", "non.lobortis.quis@ornare.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Skyhawk", "Luxuoso", "Sedan", "preto", "eget@id.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Town Car", "Confortavel", "SUV", "vermelho", "ipsum.leo@mauris.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Continental", "Confortavel", "Hatch", "vermelho", "vestibulum.lorem@adipiscing.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mark VII", "Basico", "Perua/Van", "vermelho", "dictum@Seddiamlorem.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Quattroporte", "Luxuoso", "Sedan", "amarelo", "eget@Sedeget.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Biturbo", "Luxuoso", "SUV", "azul", "dolor.dolor.tempus@ullamcorperviverraMaecenas.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("900", "Basico", "SUV", "prata", "semper.egestas.urna@sitamet.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("5000S", "Basico", "SUV", "preto", "at.augue@accumsan.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("CR-X", "Confortavel", "Hatch", "verde", "luctus.aliquet.odio@a.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Prelude", "Basico", "Sedan", "preto", "quis.accumsan@Aeneanegestashendrerit.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Daytona", "Confortavel", "Hatch", "prata", "bibendum.Donec.felis@doloregestas.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("SJ 410", "Confortavel", "Sedan", "amarelo", "non.enim.commodo@rhoncusProinnisl.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("GLC", "Luxuoso", "Perua/Van", "amarelo", "lobortis@nonummyipsum.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Somerset", "Confortavel", "Perua/Van", "prata", "Quisque.ac@Sedmolestie.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("LeSabre", "Basico", "SUV", "branco", "cursus.et.eros@dignissimMaecenas.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Regal", "Luxuoso", "Sedan", "verde", "nascetur.ridiculus.mus@tortornibhsit.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Skylark", "Basico", "Sedan", "prata", "erat.volutpat@ac.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("F-Series", "Basico", "Perua/Van", "branco", "tempus.non@estmollisnon.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Truck", "Basico", "Sedan", "branco", "lobortis.quam@atortorNunc.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Chariot", "Basico", "Perua/Van", "preto", "fermentum@augueeutellus.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Passat", "Basico", "Hatch", "amarelo", "elit@tortordictum.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Type 2", "Luxuoso", "Perua/Van", "prata", "metus@auguemalesuadamalesuada.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("4000s", "Luxuoso", "Perua/Van", "branco", "hendrerit.a@milaciniamattis.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Quattro", "Luxuoso", "Sedan", "amarelo", "quis.accumsan@ametdiam.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Coupe GT", "Luxuoso", "SUV", "preto", "Donec.est.Nunc@tristiqueaceleifend.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Countach", "Confortavel", "Hatch", "branco", "ac.nulla.In@nectempus.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Familia", "Basico", "SUV", "amarelo", "risus.Donec@enimmitempor.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("B2000", "Luxuoso", "Sedan", "preto", "mollis.Duis.sit@enimMaurisquis.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Grand Am", "Basico", "Hatch", "prata", "Nunc.quis.arcu@afacilisis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("XT", "Basico", "Hatch", "vermelho", "Integer.in.magna@est.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Leone", "Confortavel", "Hatch", "amarelo", "malesuada@mauris.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("XR4Ti", "Confortavel", "SUV", "amarelo", "vitae@Maurisvelturpis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("911", "Luxuoso", "Sedan", "prata", "magna@turpisegestasAliquam.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("928", "Basico", "Sedan", "preto", "pede.Praesent@etmalesuadafames.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Cultus", "Basico", "Perua/Van", "azul", "ante.ipsum.primis@MaurisnullaInteger.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("SJ", "Basico", "Sedan", "verde", "interdum@acfermentum.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("MR2", "Confortavel", "Perua/Van", "verde", "nulla.Integer.vulputate@dignissimMaecenas.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Esprit", "Confortavel", "Hatch", "verde", "in.molestie@eleifendCrassed.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Caravan", "Confortavel", "Hatch", "preto", "faucibus.ut@Nullamsuscipit.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Taurus", "Confortavel", "SUV", "prata", "tincidunt.dui@arcu.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Aerostar", "Basico", "Sedan", "vermelho", "elit.pretium.et@diamluctuslobortis.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Courier", "Luxuoso", "Perua/Van", "prata", "tempor@lacusvariuset.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mighty Max", "Luxuoso", "SUV", "prata", "ac@sagittissemper.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Precis", "Confortavel", "Sedan", "prata", "sagittis.augue@sedturpis.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Safari", "Confortavel", "Hatch", "azul", "Proin@at.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Gemini", "Confortavel", "Perua/Van", "vermelho", "arcu@est.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Firebird Trans Am", "Confortavel", "Hatch", "verde", "orci@inceptoshymenaeos.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("5000CS Quattro", "Basico", "Hatch", "vermelho", "odio@massanonante.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("4000s Quattro", "Basico", "SUV", "verde", "id.risus.quis@vulputateveliteu.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("4000CS Quattro", "Basico", "SUV", "verde", "sem.mollis.dui@quamdignissimpharetra.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Sable", "Confortavel", "Hatch", "prata", "luctus@euismod.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("B-Series", "Confortavel", "SUV", "preto", "consectetuer.mauris.id@Seddiamlorem.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("9000", "Basico", "SUV", "azul", "vitae.mauris.sit@sapienCras.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Range Rover", "Luxuoso", "Hatch", "amarelo", "lobortis@Proinmi.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("4000", "Confortavel", "Perua/Van", "verde", "cursus@Donectempuslorem.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("5000CS", "Basico", "SUV", "vermelho", "aliquam@tellus.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("929", "Basico", "Hatch", "vermelho", "tincidunt.Donec.vitae@DonecegestasDuis.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("B2600", "Confortavel", "Hatch", "branco", "lacinia.orci.consectetuer@Crasloremlorem.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Fox", "Luxuoso", "Perua/Van", "vermelho", "penatibus@facilisiSed.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Swift", "Confortavel", "Perua/Van", "preto", "Praesent@sagittis.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Justy", "Confortavel", "Hatch", "branco", "convallis@Aliquam.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("924 S", "Basico", "Perua/Van", "amarelo", "pede.blandit@ornareFusce.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Chevette", "Basico", "SUV", "prata", "luctus.ipsum.leo@semperegestas.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("L300", "Luxuoso", "Sedan", "branco", "Etiam@dictum.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Legend", "Basico", "Hatch", "branco", "laoreet.ipsum@rhoncusNullamvelit.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Integra", "Basico", "Hatch", "branco", "lorem.fringilla.ornare@interdumliberodui.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("924", "Confortavel", "SUV", "amarelo", "Nulla@aliquetPhasellus.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Turbo Firefly", "Luxuoso", "Hatch", "azul", "sapien.imperdiet.ornare@convallisconvallis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Tracer", "Basico", "SUV", "azul", "morbi@nascetur.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Reatta", "Luxuoso", "Sedan", "verde", "auctor@interdumCurabitur.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Festiva", "Luxuoso", "Hatch", "amarelo", "ante.bibendum.ullamcorper@Sedneque.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("MX-6", "Luxuoso", "SUV", "amarelo", "purus.Nullam@iderat.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("90", "Confortavel", "Hatch", "verde", "Integer@libero.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("80/90", "Luxuoso", "Sedan", "amarelo", "velit.eget@Phaselluselitpede.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Estate", "Luxuoso", "SUV", "azul", "pede@liberoatauctor.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Probe", "Basico", "Hatch", "verde", "sed.turpis.nec@lobortisultrices.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("MPV", "Confortavel", "Perua/Van", "vermelho", "Donec@risus.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Sigma", "Basico", "Perua/Van", "preto", "nisl.Nulla@Vestibulumanteipsum.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Eclipse", "Basico", "Perua/Van", "prata", "Fusce.aliquet@faucibus.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Legacy", "Basico", "SUV", "branco", "imperdiet.nec.leo@eratnonummyultricies.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Sidekick", "Basico", "Sedan", "branco", "amet.dapibus.id@et.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("ES", "Luxuoso", "SUV", "azul", "elementum@CraspellentesqueSed.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("228", "Luxuoso", "SUV", "branco", "quam@ipsum.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("430", "Luxuoso", "Hatch", "azul", "ante.Maecenas@enimCurabitur.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Spyder", "Confortavel", "SUV", "azul", "Maecenas.libero@fermentumarcu.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Karif", "Confortavel", "Sedan", "preto", "et@ipsumSuspendissenon.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("80", "Basico", "Sedan", "vermelho", "risus.odio.auctor@euismodmauris.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("100", "Basico", "Sedan", "azul", "magna@afeugiat.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("200", "Basico", "Sedan", "preto", "nulla.Integer@nuncrisusvarius.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Truck Xtracab SR5", "Basico", "Perua/Van", "branco", "urna.Vivamus.molestie@CuraePhasellus.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("6 Series", "Basico", "Perua/Van", "amarelo", "consectetuer@estvitaesodales.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Coachbuilder", "Basico", "Hatch", "amarelo", "taciti.sociosqu@ligula.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Loyale", "Basico", "Sedan", "azul", "faucibus@ipsum.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("MX-5", "Luxuoso", "SUV", "vermelho", "rutrum@metusInnec.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("V8", "Confortavel", "Perua/Van", "branco", "Suspendisse.tristique.neque@arcuSedet.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Coupe Quattro", "Luxuoso", "Hatch", "amarelo", "dolor.Nulla.semper@elitpellentesque.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Elan", "Confortavel", "Hatch", "verde", "morbi.tristique@netusetmalesuada.com");
