INSERT INTO grupo (nome, categoria, email_criador) VALUES ("nisi sem", "Grupo de Caronas", "quis.tristique.ac@cursus.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("feugiat metus", "Grupo de Amigos", "rutrum@turpisvitaepurus.com");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("tempus non", "Grupo de Amigos", "quis@facilisis.com");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("Donec at", "Grupo Publico", "tortor@interdumSedauctor.net");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("dui Cras", "Grupo Publico", "at.nisi@utodiovel.ca");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("nibh lacinia", "Grupo Publico", "eros.turpis.non@magna.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("cursus", "Grupo de Caravanas", "nec@lacus.edu");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("pede", "Grupo de Caronas", "feugiat@Praesent.com");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("consectetuer", "Grupo de Caronas", "nec.ante@nullaat.com");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("ligula", "Grupo Publico", "neque.venenatis@rutrumjustoPraesent.co.uk");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("dolor", "Grupo de Caronas", "ultrices.Vivamus@elitdictum.com");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("Suspendisse", "Grupo de Amigos", "Praesent.interdum@adipiscingelit.net");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("mollis", "Grupo de Caronas", "egestas.Aliquam@aliquet.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("Nam interdum", "Grupo de Caravanas", "dolor@aliquetmagna.co.uk");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("mi ac", "Grupo de Caravanas", "rhoncus.id@Etiambibendum.co.uk");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("lectus", "Grupo de Amigos", "blandit@ridic(ulusmusAenean.co.uk");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("In", "Grupo Publico", "est.Nunc.laoreet@acmi.net");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("Cum sociis", "Grupo de Amigos", "sit@arcu.com");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("dignissim tempor", "Grupo Publico", "eget@lobortis.com");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("vitae", "Grupo de Amigos", "lacinia.vitae.sodales@ametnulla.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("semper Nam", "Grupo de Caronas", "Nunc.ullamcorper.velit@velconvallis.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("tempus non", "Grupo de Caronas", "Aliquam.gravida.mauris@ipsumprimis.com");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("at", "Grupo Publico", "habitant.morbi@eu.net");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("parturient", "Grupo de Amigos", "sodales.elit@etnetus.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("faucibus", "Grupo de Caronas", "Nullam.velit.dui@elitEtiamlaoreet.edu");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("eu erat", "Grupo de Amigos", "lectus@est.edu");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("lobortis quam", "Grupo de Caravanas", "natoque.penatibus@iaculisaliquet.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("molestie Sed", "Grupo de Caravanas", "dictum.sapien.Aenean@InloremDonec.net");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("enim", "Grupo de Amigos", "et.magnis@congueelit.ca");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("Aliquam erat", "Grupo de Caronas", "pede.Cras.vulputate@euismodurna.edu");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("metus eu", "Grupo Publico", "aptent.taciti@velmaurisInteger.edu");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("libero Integer", "Grupo de Caronas", "mattis.Integer.eu@pellentesqueeget.co.uk");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("neque Morbi", "Grupo de Caronas", "augue.scelerisque.mollis@id.com");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("enim diam", "Grupo de Caronas", "libero.mauris.aliquam@magnisdis.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("in lobortis", "Grupo de Caronas", "fermentum.vel@semutcursus.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("a", "Grupo Publico", "magna@eratvolutpatNulla.edu");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("risus Donec", "Grupo de Caronas", "malesuada@lectus.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("elit Nulla", "Grupo de Caravanas", "et@pedesagittis.edu");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("Aliquam", "Grupo de Caravanas", "Duis.gravida.Praesent@tincidunt.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("molestie", "Grupo de Caronas", "nec.leo.Morbi@lobortisultrices.com");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("elit", "Grupo de Caravanas", "eget.dictum@neque.net");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("aliquam", "Grupo Publico", "odio@auctornunc.ca");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("Suspendisse", "Grupo Publico", "mauris.sapien@atlibero.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("sapien", "Grupo de Caronas", "vulputate.posuere@tellus.edu");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("elit Nulla", "Grupo de Amigos", "vulputate.nisi@Suspendissenonleo.ca");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("amet", "Grupo de Caravanas", "elit.pellentesque@ametnullaDonec.net");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("dolor", "Grupo de Amigos", "tellus.lorem@eget.net");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("tristque pellentesque", "Grupo de Caravanas", "dolor.sit@orcilacusvestibulum.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("Fusce aliquet", "Grupo de Amigos", "non.magna@montesnascetur.org");
INSERT INTO grupo (nome, categoria, email_criador) VALUES ("massa", "Grupo de Caronas", "non@arcuimperdiet.edu");
