INSERT INTO info_modelo (`marca`, `modelo`, `lugares`) VALUES ('Ford', 'Model T', '4'),
('Chrysler', 'Imperial', '4'),
('Citroën', '2CV', '4'),
('Hillman', 'Minx Magnificent', '4'),
('Chevrolet', 'Corvette', '4'),
('Cadillac', 'Fleetwood', '4'),
('Ford', 'Thunderbird', '4'),
('BMW', '600', '4'),
('Austin', 'Mini', '4'),
('Chevrolet', 'Corvair', '4'),
('Fillmore', 'Fillmore', '4'),
('Fairthorpe', 'Rockette', '4'),
('Austin', 'Mini Cooper', '4'),
('Studebaker', 'Avanti', '4'),
('Pontiac', 'Tempest', '4'),
('Pontiac', 'Grand Prix', '4'),
('Buick', 'Special', '4'),
('Austin', 'Mini Cooper S', '4'),
('Ford', 'E-Series', '4'),
('Chevrolet', 'Corvair 500', '4'),
('Ford', 'Mustang', '4'),
('Ford', 'Galaxie', '4'),
('Pontiac', 'LeMans', '4'),
('Pontiac', 'Bonneville', '4'),
('Ford', 'Fairlane', '4'),
('Volkswagen', 'Beetle', '4'),
('Ford', 'Falcon', '4'),
('Jensen', 'Interceptor', '4'),
('Oldsmobile', 'Toronado', '4'),
('Pontiac', 'Firebird', '4'),
('Chevrolet', 'Camaro', '4'),
('Chevrolet', 'Bel Air', '4'),
('Ford', 'Country', '4'),
('Mercury', 'Cougar', '4'),
('Dodge', 'Charger', '4'),
('Shelby', 'GT350', '4'),
('Ford', 'Torino', '4'),
('Porsche', '914', '4'),
('Chevrolet', 'Vega', '4'),
('Citroën', 'SM', '4'),
('Chevrolet', 'Monte Carlo', '4'),
('Citroën', 'CX', '4'),
('Chevrolet', 'Monza', '4'),
('Volkswagen', 'Golf', '4'),
('Toyota', 'Celica', '4'),
('Chevrolet', 'Caprice', '4'),
('Mercedes-Benz', 'W123', '4'),
('MG', 'MGB', '4'),
('Dodge', 'Omni', '4'),
('Nissan', '280ZX', '4'),
('Chevrolet', 'LUV', '4'),
('Buick', 'Riviera', '4'),
('Chevrolet', 'Citation', '4'),
('Honda', 'Civic', '4'),
('Dodge', 'Aries', '4'),
('Mercedes-Benz', 'W126', '4'),
('Pontiac', '6000', '4'),
('Pontiac', 'Sunbird', '4'),
('Honda', 'Accord', '4'),
('Renault', 'Alliance', '4'),
('Mazda', '626', '4'),
('Mazda', 'RX-7', '4'),
('Porsche', '944', '4'),
('Pontiac', '1000', '4'),
('Pontiac', 'Parisienne', '4'),
('Pontiac', 'Fiero', '4'),
('Pontiac', 'Firefly', '4'),
('Ford', 'Bronco II', '4'),
('Ford', 'Laser', '4'),
('Ford', 'EXP', '4'),
('Ford', 'Ranger', '4'),
('Ford', 'Escort', '4'),
('Ford', 'Tempo', '4'),
('Ford', 'LTD', '4'),
('Ford', 'F250', '4'),
('Ford', 'F150', '4'),
('Ford', 'E250', '4'),
('Ford', 'LTD Crown Victoria', '4'),
('Ford', 'Bronco', '4'),
('Ford', 'E150', '4'),
('Mitsubishi', 'Galant', '4'),
('Mitsubishi', 'Mirage', '4'),
('Mitsubishi', 'Starion', '4'),
('Mitsubishi', 'Pajero', '4'),
('Mitsubishi', 'Cordia', '4'),
('Mitsubishi', 'Tredia', '4'),
('Subaru', 'Brat', '4'),
('Mercedes-Benz', 'S-Class', '4'),
('Mercedes-Benz', 'E-Class', '4'),
('Mercedes-Benz', 'W201', '4'),
('Mercedes-Benz', 'SL-Class', '4'),
('Mercury', 'Topaz', '4'),
('Mercury', 'Grand Marquis', '4'),
('Mercury', 'Lynx', '4'),
('Mercury', 'Capri', '4'),
('Mercury', 'Marquis', '4'),
('Lotus', 'Esprit Turbo', '4'),
('Volkswagen', 'Jetta', '4'),
('Volkswagen', 'Vanagon', '4'),
('Volkswagen', 'Scirocco', '4'),
('Volkswagen', 'Quantum', '4'),
('Buick', 'Electra', '4'),
('Buick', 'Century', '4'),
('Buick', 'Skyhawk', '4'),
('Lincoln', 'Town Car', '4'),
('Lincoln', 'Continental', '4'),
('Lincoln', 'Mark VII', '4'),
('Maserati', 'Quattroporte', '4'),
('Maserati', 'Biturbo', '4'),
('Saab', '900', '4'),
('Audi', '5000S', '4'),
('Honda', 'CR-X', '4'),
('Honda', 'Prelude', '4'),
('Dodge', 'Daytona', '4'),
('Suzuki', 'SJ 410', '4'),
('Mazda', 'GLC', '4'),
('Buick', 'Somerset', '4'),
('Buick', 'LeSabre', '4'),
('Buick', 'Regal', '4'),
('Buick', 'Skylark', '4'),
('Ford', 'F-Series', '4'),
('Mitsubishi', 'Truck', '4'),
('Mitsubishi', 'Chariot', '4'),
('Volkswagen', 'Passat', '4'),
('Volkswagen', 'Type 2', '4'),
('Audi', '4000s', '4'),
('Audi', 'Quattro', '4'),
('Audi', 'Coupe GT', '4'),
('Lamborghini', 'Countach', '4'),
('Mazda', 'Familia', '4'),
('Mazda', 'B2000', '4'),
('Pontiac', 'Grand Am', '4'),
('Subaru', 'XT', '4'),
('Subaru', 'Leone', '4'),
('Merkur', 'XR4Ti', '4'),
('Porsche', '911', '4'),
('Porsche', '928', '4'),
('Suzuki', 'Cultus', '4'),
('Suzuki', 'SJ', '4'),
('Toyota', 'MR2', '4'),
('Lotus', 'Esprit', '4'),
('Dodge', 'Caravan', '4'),
('Ford', 'Taurus', '4'),
('Ford', 'Aerostar', '4'),
('Ford', 'Courier', '4'),
('Mitsubishi', 'Mighty Max', '4'),
('Mitsubishi', 'Precis', '4'),
('Pontiac', 'Safari', '4'),
('Pontiac', 'Gemini', '4'),
('Pontiac', 'Firebird Trans Am', '4'),
('Audi', '5000CS Quattro', '4'),
('Audi', '4000s Quattro', '4'),
('Audi', '4000CS Quattro', '4'),
('Mercury', 'Sable', '4'),
('Mazda', 'B-Series', '4'),
('Saab', '9000', '4'),
('Land Rover', 'Range Rover', '4'),
('Audi', '4000', '4'),
('Audi', '5000CS', '4'),
('Mazda', '929', '4'),
('Mazda', 'B2600', '4'),
('Volkswagen', 'Fox', '4'),
('Suzuki', 'Swift', '4'),
('Subaru', 'Justy', '4'),
('Porsche', '924 S', '4'),
('Pontiac', 'Chevette', '4'),
('Mitsubishi', 'L300', '4'),
('Acura', 'Legend', '4'),
('Acura', 'Integra', '4'),
('Porsche', '924', '4'),
('Pontiac', 'Turbo Firefly', '4'),
('Mercury', 'Tracer', '4'),
('Buick', 'Reatta', '4'),
('Ford', 'Festiva', '4'),
('Mazda', 'MX-6', '4'),
('Audi', '90', '4'),
('Audi', '80/90', '4'),
('Buick', 'Estate', '4'),
('Ford', 'Probe', '4'),
('Mazda', 'MPV', '4'),
('Mitsubishi', 'Sigma', '4'),
('Mitsubishi', 'Eclipse', '4'),
('Subaru', 'Legacy', '4'),
('Suzuki', 'Sidekick', '4'),
('Lexus', 'ES', '4'),
('Maserati', '228', '4'),
('Maserati', '430', '4'),
('Maserati', 'Spyder', '4'),
('Maserati', 'Karif', '4'),
('Audi', '80', '4'),
('Audi', '100', '4'),
('Audi', '200', '4'),
('Toyota', 'Truck Xtracab SR5', '4'),
('BMW', '6 Series', '4'),
('Buick', 'Coachbuilder', '4'),
('Subaru', 'Loyale', '4'),
('Mazda', 'MX-5', '4'),
('Audi', 'V8', '4'),
('Audi', 'Coupe Quattro', '4'),
('Lotus', 'Elan', '4'),
('Volkswagen', 'Corrado', '4'),
('Mitsubishi', 'GTO', '4'),
('Nissan', 'Maxima', '4'),
('Nissan', 'Datsun/Nissan Z-car', '4'),
('Lamborghini', 'Diablo', '4'),
('Eagle', 'Talon', '4'),
('Ford', 'Explorer', '4'),
('Buick', 'Park Avenue', '4'),
('Buick', 'Roadmaster', '4'),
('Mazda', 'Navajo', '4'),
('Nissan', '300ZX', '4'),
('Nissan', 'Sentra', '4'),
('Land Rover', 'Sterling', '4'),
('Toyota', 'Previa', '4'),
('Volkswagen', 'Eurovan', '4'),
('Ford', 'Crown Victoria', '4'),
('Ford', 'Club Wagon', '4'),
('Ford', 'Econoline E150', '4'),
('Ford', 'Econoline E250', '4'),
('Ford', 'Econoline E350', '4'),
('Ford', 'F350', '4'),
('Suzuki', 'Samurai', '4'),
('Mercedes-Benz', '190E', '4'),
('Mercedes-Benz', '300CE', '4'),
('Mercedes-Benz', '300D', '4'),
('Mercedes-Benz', '300E', '4'),
('Mercedes-Benz', '300SD', '4'),
('Mercedes-Benz', '300SE', '4'),
('Mercedes-Benz', '300SL', '4'),
('Mercedes-Benz', '300TE', '4'),
('Mercedes-Benz', '400E', '4'),
('Mercedes-Benz', '400SE', '4'),
('Mercedes-Benz', '500E', '4'),
('Mercedes-Benz', '500SEL', '4'),
('Mercedes-Benz', '500SL', '4'),
('Mercedes-Benz', '600SEL', '4'),
('Subaru', 'Alcyone SVX', '4'),
('Subaru', 'SVX', '4'),
('Mitsubishi', 'Diamante', '4'),
('Mitsubishi', 'RVR', '4'),
('Mitsubishi', '3000GT', '4'),
('Mitsubishi', 'Expo', '4'),
('Mitsubishi', 'Mighty Max Macro', '4'),
('Mitsubishi', 'Montero', '4'),
('Mazda', '323', '4'),
('Mazda', 'Protege', '4'),
('Mazda', 'MX-3', '4'),
('Mazda', 'B-Series Plus', '4'),
('Mazda', 'Miata MX-5', '4'),
('Audi', 'S4', '4'),
('BMW', '3 Series', '4'),
('BMW', '5 Series', '4'),
('BMW', '7 Series', '4'),
('BMW', '8 Series', '4'),
('BMW', 'M5', '4'),
('Pontiac', 'Firebird Formula', '4'),
('Land Rover', 'Defender', '4'),
('Dodge', 'Viper', '4'),
('Dodge', 'D150 Club', '4'),
('Dodge', 'D150', '4'),
('Dodge', 'D250 Club', '4'),
('Dodge', 'D250', '4'),
('Dodge', 'D350 Club', '4'),
('Dodge', 'D350', '4'),
('Dodge', 'Dakota Club', '4'),
('Dodge', 'Dakota', '4'),
('Dodge', 'Dynasty', '4'),
('Dodge', 'Grand Caravan', '4'),
('Dodge', 'Monaco', '4'),
('Dodge', 'Ram 50', '4'),
('Dodge', 'Ram Van B150', '4'),
('Dodge', 'Ram Van B250', '4'),
('Dodge', 'Ram Van B350', '4'),
('Dodge', 'Ram Wagon B150', '4'),
('Dodge', 'Ram Wagon B250', '4'),
('Dodge', 'Ram Wagon B350', '4'),
('Dodge', 'Ramcharger', '4'),
('Dodge', 'Shadow', '4'),
('Dodge', 'Spirit', '4'),
('Dodge', 'Stealth', '4'),
('Porsche', '968', '4'),
('Cadillac', 'Seville', '4'),
('Cadillac', 'Allante', '4'),
('Cadillac', 'Brougham', '4'),
('Cadillac', 'DeVille', '4'),
('Cadillac', 'Eldorado', '4'),
('Toyota', 'Camry', '4'),
('Toyota', '4Runner', '4'),
('Toyota', 'Corolla', '4'),
('Toyota', 'Cressida', '4'),
('Toyota', 'Land Cruiser', '4'),
('Toyota', 'Paseo', '4'),
('Toyota', 'Supra', '4'),
('Toyota', 'Tercel', '4'),
('Toyota', 'Xtra', '4'),
('Nissan', '240SX', '4'),
('Nissan', 'NX', '4'),
('Nissan', 'Pathfinder', '4'),
('Nissan', 'Stanza', '4'),
('Chevrolet', '1500', '4'),
('Chevrolet', '2500', '4'),
('Chevrolet', '3500', '4'),
('Chevrolet', 'APV', '4'),
('Chevrolet', 'Astro', '4'),
('Chevrolet', 'Beretta', '4'),
('Chevrolet', 'Blazer', '4'),
('Chevrolet', 'Cavalier', '4'),
('Chevrolet', 'Corsica', '4'),
('Chevrolet', 'G-Series G10', '4'),
('Chevrolet', 'G-Series G20', '4'),
('Chevrolet', 'G-Series G30', '4'),
('Chevrolet', 'Lumina', '4'),
('Chevrolet', 'Lumina APV', '4'),
('Chevrolet', 'S10 Blazer', '4'),
('Chevrolet', 'S10', '4'),
('Chevrolet', 'Sportvan G10', '4'),
('Chevrolet', 'Sportvan G20', '4'),
('Chevrolet', 'Sportvan G30', '4'),
('Chevrolet', 'Suburban 1500', '4'),
('Chevrolet', 'Suburban 2500', '4'),
('Chrysler', 'Fifth Ave', '4'),
('Chrysler', 'LeBaron', '4'),
('Chrysler', 'New Yorker', '4'),
('Chrysler', 'Town & Country', '4'),
('Daihatsu', 'Charade', '4'),
('Daihatsu', 'Rocky', '4'),
('Hyundai', 'Elantra', '4'),
('Hyundai', 'Excel', '4'),
('Hyundai', 'Scoupe', '4'),
('Hyundai', 'Sonata', '4'),
('Infiniti', 'G', '4'),
('Infiniti', 'M', '4'),
('Infiniti', 'Q', '4'),
('Isuzu', 'Amigo', '4'),
('Isuzu', 'Impulse', '4'),
('Isuzu', 'Rodeo', '4'),
('Isuzu', 'Stylus', '4'),
('Isuzu', 'Trooper', '4'),
('Jaguar', 'XJ Series', '4'),
('Jeep', 'Cherokee', '4'),
('Jeep', 'Comanche', '4'),
('Jeep', 'Wrangler', '4'),
('Oldsmobile', '88', '4'),
('Oldsmobile', '98', '4'),
('Oldsmobile', 'Achieva', '4'),
('Oldsmobile', 'Bravada', '4'),
('Oldsmobile', 'Ciera', '4'),
('Oldsmobile', 'Custom Cruiser', '4'),
('Oldsmobile', 'Cutlass Supreme', '4'),
('Oldsmobile', 'Silhouette', '4'),
('Saturn', 'S-Series', '4'),
('Subaru', 'Impreza', '4'),
('Mercury', 'Villager', '4'),
('Mercedes-Benz', 'C-Class', '4'),
('Mercedes-Benz', '400SEL', '4'),
('Mercedes-Benz', '500SEC', '4'),
('Mercedes-Benz', '600SEC', '4'),
('Mercedes-Benz', '600SL', '4'),
('Dodge', 'Viper RT/10', '4'),
('Dodge', 'Intrepid', '4'),
('Volkswagen', 'Golf III', '4'),
('Volkswagen', 'Jetta III', '4'),
('Land Rover', 'Range Rover Classic', '4'),
('Land Rover', 'Defender 110', '4'),
('Nissan', 'Altima', '4'),
('Nissan', 'Quest', '4'),
('Lincoln', 'Mark VIII', '4'),
('Lexus', 'GS', '4'),
('Chrysler', 'Concorde', '4'),
('Honda', 'del Sol', '4'),
('Toyota', 'T100', '4'),
('Jeep', 'Grand Cherokee', '4'),
('Cadillac', 'Sixty Special', '4'),
('Chevrolet', 'Caprice Classic', '4'),
('Eagle', 'Vision', '4'),
('GMC', 'Sonoma Club Coupe', '4'),
('HUMMER', 'H1', '4'),
('Infiniti', 'J', '4'),
('Oldsmobile', 'Cutlass Cruiser', '4'),
('Volvo', '850', '4'),
('Ford', 'Lightning', '4'),
('Ford', 'Aspire', '4'),
('Kia', 'Sephia', '4'),
('Dodge', 'Ram', '4'),
('Dodge', 'Ram 1500', '4'),
('Dodge', 'Ram 2500', '4'),
('Dodge', 'Ram 3500', '4'),
('Chevrolet', 'Impala SS', '4'),
('Chevrolet', 'Impala', '4'),
('Audi', 'Cabriolet', '4'),
('Audi', 'riolet', '4'),
('Land Rover', 'Discovery', '4'),
('Land Rover', 'Defender 90', '4'),
('Honda', 'Passport', '4'),
('Chrysler', 'LHS', '4'),
('Kia', 'Sportage', '4'),
('Pontiac', 'Sunfire', '4'),
('Ford', 'Windstar', '4'),
('Ford', 'Contour', '4'),
('Volkswagen', 'rio', '4'),
('Mercury', 'Mystique', '4'),
('Suzuki', 'Esteem', '4'),
('Mazda', 'Millenia', '4'),
('Audi', 'S6', '4'),
('Audi', 'A6', '4'),
('Acura', 'TL', '4'),
('BMW', 'M3', '4'),
('Dodge', 'Avenger', '4'),
('Dodge', 'Neon', '4'),
('Dodge', 'Ram 1500 Club', '4'),
('Dodge', 'Ram 2500 Club', '4'),
('Dodge', 'Ram 3500 Club', '4'),
('Dodge', 'Ram Van 1500', '4'),
('Dodge', 'Ram Van 2500', '4'),
('Dodge', 'Ram Van 3500', '4'),
('Dodge', 'Stratus', '4'),
('Nissan', '200SX', '4'),
('Chevrolet', 'K5 Blazer', '4'),
('Chevrolet', 'Tahoe', '4'),
('Honda', 'Odyssey', '4'),
('Chrysler', 'Cirrus', '4'),
('Chrysler', 'Sebring', '4'),
('Holden', 'VS Commodore', '4'),
('GMC', 'Rally Wagon G2500', '4'),
('GMC', 'Rally Wagon G3500', '4'),
('GMC', 'Vandura G1500', '4'),
('GMC', 'Vandura G2500', '4'),
('GMC', 'Vandura G3500', '4'),
('Hyundai', 'Accent', '4'),
('Oldsmobile', 'Aurora', '4'),
('Toyota', 'Avalon', '4'),
('Toyota', 'T100 Xtra', '4'),
('Toyota', 'Tacoma', '4'),
('Toyota', 'Tacoma Xtra', '4'),
('Buick', 'Hearse', '4'),
('Audi', 'A4', '4'),
('Mitsubishi', 'Expo LRV', '4'),
('Suzuki', 'X-90', '4'),
('Chevrolet', 'Express 1500', '4'),
('Chevrolet', 'Express 2500', '4'),
('Chevrolet', 'Express 3500', '4'),
('Chevrolet', 'G-Series 1500', '4'),
('Chevrolet', 'G-Series 2500', '4'),
('Lexus', 'LX', '4'),
('BMW', 'Z3', '4'),
('Acura', 'RL', '4'),
('Acura', 'SLX', '4'),
('GMC', 'Savana 1500', '4'),
('GMC', 'Savana 2500', '4'),
('GMC', 'Savana 3500', '4'),
('Infiniti', 'I', '4'),
('Isuzu', 'Hombre', '4'),
('Isuzu', 'Oasis', '4'),
('Toyota', 'RAV4', '4'),
('Kia', 'Mentor', '4'),
('Mercury', 'Mountaineer', '4'),
('Honda', 'CR-V', '4'),
('Audi', 'A8', '4'),
('Mitsubishi', 'Challenger', '4'),
('Mitsubishi', 'Montero Sport', '4'),
('Porsche', 'Boxster', '4'),
('Mercedes-Benz', 'SLK-Class', '4'),
('Ford', 'Expedition', '4'),
('Chevrolet', 'Malibu', '4'),
('Chevrolet', 'G-Series 3500', '4'),
('Chevrolet', 'Venture', '4'),
('Acura', 'CL', '4'),
('Cadillac', 'Catera', '4'),
('Hyundai', 'Tiburon', '4'),
('Infiniti', 'QX', '4'),
('Isuzu', 'Hombre Space', '4'),
('Jaguar', 'XK Series', '4'),
('Oldsmobile', 'Cutlass', '4'),
('Oldsmobile', 'LSS', '4'),
('Oldsmobile', 'Regency', '4'),
('Volvo', 'S90', '4'),
('Volvo', 'V90', '4'),
('Chevrolet', 'Metro', '4'),
('Chevrolet', 'Prizm', '4'),
('Chevrolet', 'Tracker', '4'),
('Subaru', 'Forester', '4'),
('Volkswagen', 'New Beetle', '4'),
('Lincoln', 'Navigator', '4'),
('Mercedes-Benz', 'M-Class', '4'),
('Mercedes-Benz', 'CL-Class', '4'),
('Mercedes-Benz', 'CLK-Class', '4'),
('Dodge', 'Durango', '4'),
('GMC', 'Envoy', '4'),
('Nissan', 'Frontier', '4'),
('Oldsmobile', 'Intrigue', '4'),
('Toyota', 'Sienna', '4'),
('Volvo', 'C70', '4'),
('Volvo', 'S70', '4'),
('Volvo', 'V70', '4'),
('Chevrolet', 'Silverado', '4'),
('Chevrolet', 'Silverado 1500', '4'),
('Chevrolet', 'Silverado 2500', '4'),
('Pontiac', 'Montana', '4'),
('Suzuki', 'Vitara', '4'),
('Suzuki', 'Grand Vitara', '4'),
('Land Rover', 'Discovery Series II', '4'),
('Saab', '9-3', '4'),
('Saab', '9-5', '4'),
('Lexus', 'RX', '4'),
('GMC', 'EV1', '4'),
('GMC', 'Sierra 1500', '4'),
('GMC', 'Sierra 2500', '4'),
('Chrysler', '300M', '4'),
('Corbin', 'Sparrow', '4'),
('Cadillac', 'Escalade', '4'),
('Chrysler', '300', '4'),
('Daewoo', 'Lanos', '4'),
('Daewoo', 'Leganza', '4'),
('Daewoo', 'Nubira', '4'),
('Isuzu', 'VehiCROSS', '4'),
('Oldsmobile', 'Alero', '4'),
('Toyota', 'Solara', '4'),
('Volvo', 'S80', '4'),
('Subaru', 'Outback', '4'),
('Honda', 'Insight', '4'),
('Honda', 'S2000', '4'),
('BMW', 'X5', '4'),
('BMW', 'Z8', '4'),
('Kia', 'Spectra', '4'),
('Lincoln', 'LS', '4'),
('Ford', 'Th!nk', '4'),
('Ford', 'Explorer Sport Trac', '4'),
('Ford', 'Escape', '4'),
('Ford', 'Excursion', '4'),
('Ford', 'Explorer Sport', '4'),
('Ford', 'Focus', '4'),
('Audi', 'TT', '4'),
('Toyota', 'Tundra', '4'),
('Toyota', 'Ipsum', '4'),
('Toyota', 'Echo', '4'),
('Nissan', 'Xterra', '4'),
('Chrysler', 'Grand Voyager', '4'),
('Chrysler', 'Voyager', '4'),
('GMC', 'Sierra 3500', '4'),
('GMC', 'Yukon Denali', '4'),
('GMC', 'Yukon XL 1500', '4'),
('GMC', 'Yukon XL 2500', '4'),
('Jaguar', 'S-Type', '4'),
('Saturn', 'L-Series', '4'),
('Volvo', 'S40', '4'),
('Volvo', 'V40', '4'),
('Ford', 'Fiesta', '4'),
('Ford', 'ZX2', '4'),
('Suzuki', 'XL-7', '4'),
('Mazda', 'B2500', '4'),
('Mazda', 'Tribute', '4'),
('Audi', 'S8', '4'),
('Audi', 'Allroad', '4'),
('Pontiac', 'Aztek', '4'),
('Mitsubishi', 'Lancer', '4'),
('Lexus', 'IS', '4'),
('Land Rover', 'Freelander', '4'),
('BMW', '525', '4'),
('BMW', '530', '4'),
('Toyota', 'Highlander', '4'),
('Toyota', 'Prius', '4'),
('Toyota', 'Sequoia', '4'),
('Kia', 'Rio', '4'),
('Kia', 'Optima', '4'),
('Chevrolet', 'Silverado 3500', '4'),
('Acura', 'MDX', '4'),
('Chrysler', 'PT Cruiser', '4'),
('Chrysler', 'Prowler', '4'),
('Hyundai', 'Santa Fe', '4'),
('Hyundai', 'XG300', '4'),
('Isuzu', 'Rodeo Sport', '4'),
('Volvo', 'S60', '4'),
('Suzuki', 'Aerio', '4'),
('Mercedes-Benz', 'G-Class', '4'),
('Subaru', 'Outback Sport', '4'),
('Honda', 'Pilot', '4'),
('Mazda', 'Protege5', '4'),
('Mitsubishi', 'Lancer Evolution', '4'),
('Lamborghini', 'Murcielago', '4'),
('Buick', 'Rendezvous', '4'),
('BMW', '745', '4'),
('Lincoln', 'Blackwood', '4'),
('Kia', 'Sedona', '4'),
('GMC', 'Envoy XL', '4'),
('Chevrolet', 'Avalanche', '4'),
('Chevrolet', 'Trailblazer', '4'),
('Chevrolet', 'Avalanche 1500', '4'),
('Chevrolet', 'Avalanche 2500', '4'),
('MINI', 'MINI', '4'),
('MINI', 'Cooper', '4'),
('Acura', 'RSX', '4'),
('Cadillac', 'Escalade EXT', '4'),
('Hyundai', 'XG350', '4'),
('Isuzu', 'Axiom', '4'),
('Jaguar', 'X-Type', '4'),
('Jeep', 'Liberty', '4'),
('Saturn', 'VUE', '4'),
('Mercury', 'Marauder', '4'),
('BMW', '760', '4'),
('BMW', 'Z4', '4'),
('Ford', 'Escort ZX2', '4'),
('Ford', 'Freestar', '4'),
('Ford', 'E350', '4'),
('Lexus', 'GX', '4'),
('Honda', 'Element', '4'),
('Honda', 'Civic Si', '4'),
('Honda', 'Civic GX', '4'),
('Porsche', 'Cayenne', '4'),
('Mitsubishi', 'Outlander', '4'),
('Subaru', 'Baja', '4'),
('Pontiac', 'Vibe', '4'),
('Audi', 'RS6', '4'),
('Audi', 'RS 6', '4'),
('Mazda', 'Mazda6', '4'),
('Volkswagen', 'Touareg', '4'),
('Kia', 'Sorento', '4'),
('Lamborghini', 'Gallardo', '4'),
('Lincoln', 'Aviator', '4'),
('Maybach', '57', '4'),
('Maybach', '62', '4'),
('Volvo', 'XC90', '4'),
('Volvo', 'XC70', '4'),
('Chevrolet', 'SSR', '4'),
('Infiniti', 'G35', '4'),
('Infiniti', 'FX', '4'),
('Nissan', '350Z', '4'),
('Nissan', 'Murano', '4'),
('Cadillac', 'CTS', '4'),
('Cadillac', 'Escalade ESV', '4'),
('HUMMER', 'H2', '4'),
('Isuzu', 'Ascender', '4'),
('Saturn', 'Ion', '4'),
('Toyota', 'Matrix', '4'),
('Mitsubishi', 'Endeavor', '4'),
('Lotus', 'Exige', '4'),
('Lotus', 'Elise', '4'),
('Porsche', 'Carrera GT', '4'),
('Mazda', 'Mazda3', '4'),
('Mazda', 'RX-8', '4'),
('Kia', 'Amanti', '4'),
('BMW', '325', '4'),
('BMW', '545', '4'),
('BMW', '645', '4'),
('BMW', 'X3', '4'),
('Buick', 'Rainier', '4'),
('Holden', 'Monaro', '4'),
('Mercury', 'Monterey', '4'),
('Spyker', 'C8 Spyder', '4'),
('Spyker', 'C8 Spyder Wide Body', '4'),
('Spyker', 'C8 Laviolette', '4'),
('Suzuki', 'Daewoo Lacetti', '4'),
('Suzuki', 'Daewoo Magnus', '4'),
('Suzuki', 'Forenza', '4'),
('Suzuki', 'Verona', '4'),
('Volkswagen', 'R32', '4'),
('Volkswagen', 'Phaeton', '4'),
('Chevrolet', 'Aveo', '4'),
('Chevrolet', 'Colorado', '4'),
('Scion', 'xA', '4'),
('Scion', 'xB', '4'),
('Cadillac', 'SRX', '4'),
('Cadillac', 'XLR', '4'),
('Nissan', 'Titan', '4'),
('Nissan', 'Pathfinder Armada', '4'),
('Acura', 'TSX', '4'),
('Chrysler', 'Crossfire', '4'),
('Chrysler', 'Pacifica', '4'),
('GMC', 'Canyon', '4'),
('GMC', 'Envoy XUV', '4'),
('Ford', 'GT', '4'),
('Ford', 'Freestyle', '4'),
('Ford', 'Five Hundred', '4'),
('Buick', 'LaCrosse', '4'),
('Buick', 'Terraza', '4'),
('Suzuki', 'Reno', '4'),
('Mercedes-Benz', 'SLR McLaren', '4'),
('BMW', '330', '4'),
('Cadillac', 'STS', '4'),
('Maserati', 'Gran Sport', '4'),
('Maserati', 'Coupe', '4'),
('Maserati', 'GranSport', '4'),
('Chrysler', '300C', '4'),
('Mercury', 'Montego', '4'),
('Mercury', 'Mariner', '4'),
('Chevrolet', 'Cobalt', '4'),
('Chevrolet', 'Equinox', '4'),
('Chevrolet', 'Uplander', '4'),
('Land Rover', 'LR3', '4'),
('Spyker Cars', 'C8', '4'),
('Maybach', '57S', '4'),
('Saab', '9-7X', '4'),
('Saab', '9-2X', '4'),
('Dodge', 'Magnum', '4'),
('Aston Martin', 'DB9', '4'),
('Aston Martin', 'Vanquish S', '4'),
('Bentley', 'Arnage', '4'),
('Hyundai', 'Tucson', '4'),
('Nissan', 'Armada', '4'),
('Panoz', 'Esperante', '4'),
('Rolls-Royce', 'Phantom', '4'),
('Saturn', 'Relay', '4'),
('Volvo', 'V50', '4'),
('GMC', 'Sierra Denali', '4'),
('GMC', 'Sierra 3500HD', '4'),
('GMC', 'Sierra 2500HD', '4'),
('GMC', 'Yukon XL', '4'),
('GMC', 'Savana Cargo Van', '4'),
('GMC', 'Sierra Hybrid', '4'),
('GMC', 'Savana', '4'),
('Mazda', 'Mazda6 5-Door', '4'),
('Mazda', 'Mazda5', '4'),
('Mazda', 'Mazda6 Sport', '4'),
('Mazda', 'Mazdaspeed6', '4'),
('BMW', '550', '4'),
('BMW', '650', '4'),
('BMW', '750', '4'),
('BMW', 'M6', '4'),
('BMW', 'M Roadster', '4'),
('BMW', 'Z4 M', '4'),
('Mercedes-Benz', 'CLS-Class', '4'),
('Mercedes-Benz', 'G55 AMG', '4'),
('Mercedes-Benz', 'SL65 AMG', '4'),
('Mercedes-Benz', 'R-Class', '4'),
('Hyundai', 'Azera', '4'),
('Cadillac', 'DTS', '4'),
('Cadillac', 'XLR-V', '4'),
('Cadillac', 'CTS-V', '4'),
('Cadillac', 'STS-V', '4'),
('Jeep', 'Commander', '4'),
('Honda', 'Ridgeline', '4'),
('Suzuki', 'XL7', '4'),
('Buick', 'Lucerne', '4'),
('Volkswagen', 'Rabbit', '4'),
('Kia', 'Spectra5', '4'),
('Pontiac', 'Torrent', '4'),
('Pontiac', 'Solstice', '4'),
('Mitsubishi', 'Raider', '4'),
('Jaguar', 'XK', '4'),
('Jaguar', 'XJ', '4'),
('Toyota', 'Yaris', '4'),
('Toyota', 'Camry Solara', '4'),
('Subaru', 'Tribeca', '4'),
('Subaru', 'B9 Tribeca', '4'),
('Chevrolet', 'Suburban', '4'),
('Chevrolet', 'Silverado 3500HD', '4'),
('Chevrolet', 'HHR Panel', '4'),
('Chevrolet', 'Malibu Maxx', '4'),
('Chevrolet', 'HHR', '4'),
('Chevrolet', 'Silverado Hybrid', '4'),
('Chevrolet', 'Express', '4'),
('Ford', 'F-250 Super Duty', '4'),
('Ford', 'F-350 Super Duty', '4'),
('Ford', 'E-350 Super Duty', '4'),
('Ford', 'E-350 Super Duty Van', '4'),
('Ford', 'Fusion', '4'),
('Audi', 'A3', '4'),
('Land Rover', 'Range Rover Sport', '4'),
('Lexus', 'RX Hybrid', '4'),
('Porsche', 'Cayman', '4'),
('Mercury', 'Milan', '4'),
('Hummer', 'H2 SUT', '4'),
('Hummer', 'H2 SUV', '4'),
('Hummer', 'H3', '4'),
('Nissan', '350Z Roadster', '4'),
('Chrysler', 'Crossfire Roadster', '4'),
('Lincoln', 'Zephyr', '4'),
('Lincoln', 'Mark LT', '4'),
('Dodge', 'Sprinter', '4'),
('Aston Martin', 'DB9 Volante', '4'),
('Aston Martin', 'V8 Vantage', '4'),
('Aston Martin', 'Vantage', '4'),
('Spyker', 'C8 Double 12 S', '4'),
('Ferrari', 'F430', '4'),
('Ferrari', '612 Scaglietti', '4'),
('Ferrari', 'F430 Spider', '4'),
('Morgan', 'Aero 8', '4'),
('Peugeot', '207', '4'),
('Isuzu', 'i-Series', '4'),
('Isuzu', 'i-280', '4'),
('Isuzu', 'i-350', '4'),
('Chevrolet', 'Cobalt SS', '4'),
('Volkswagen', 'Eos', '4'),
('Ford', 'F-Series Super Duty', '4'),
('Ford', 'GT500', '4'),
('Ford', 'Edge', '4'),
('Ford', 'Expedition EL', '4'),
('Mercedes-Benz', 'GL-Class', '4'),
('BMW', 'Alpina B7', '4'),
('Dodge', 'Nitro', '4'),
('Dodge', 'Caliber', '4'),
('Kia', 'Carens', '4'),
('Kia', 'Rondo', '4'),
('Toyota', 'Highlander Hybrid', '4'),
('Toyota', 'Camry Hybrid', '4'),
('Toyota', 'FJ Cruiser', '4'),
('Toyota', 'TundraMax', '4'),
('Mazda', 'CX-7', '4'),
('Mazda', 'Mazdaspeed 3', '4'),
('Mazda', 'CX-9', '4'),
('Audi', 'Q7', '4'),
('Audi', 'RS4', '4'),
('Audi', 'RS 4', '4'),
('Jeep', 'Compass', '4'),
('Jeep', 'Patriot', '4'),
('Isuzu', 'i-290', '4'),
('Isuzu', 'i-370', '4'),
('Hyundai', 'Veracruz', '4'),
('Hyundai', 'Entourage', '4'),
('Foose', 'Hemisfear', '4'),
('Infiniti', 'QX56', '4'),
('Honda', 'Fit', '4'),
('Nissan', 'Versa', '4'),
('GMC', 'Acadia', '4'),
('GMC', 'Sierra', '4'),
('Suzuki', 'SX4', '4'),
('Ferrari', '599 GTB Fiorano', '4'),
('Lincoln', 'MKX', '4'),
('Lincoln', 'MKZ', '4'),
('Lincoln', 'Navigator L', '4'),
('Saturn', 'Outlook', '4'),
('Saturn', 'Aura', '4'),
('Saturn', 'Sky', '4'),
('Pontiac', 'G5', '4'),
('Acura', 'RDX', '4'),
('Chrysler', 'Aspen', '4'),
('Volvo', 'C30', '4'),
('BMW', '1 Series', '4'),
('BMW', 'X6', '4'),
('Audi', 'S5', '4'),
('Audi', 'R8', '4'),
('Audi', 'A5', '4'),
('Ford', 'Taurus X', '4'),
('Ford', 'F450', '4'),
('Volkswagen', 'GLI', '4'),
('Volkswagen', 'Touareg 2', '4'),
('Land Rover', 'LR2', '4'),
('Lexus', 'IS-F', '4'),
('Lexus', 'IS F', '4'),
('Lamborghini', 'Reventon', '4'),
('Lamborghini', 'Murcielago LP640', '4'),
('Infiniti', 'G37', '4'),
('Infiniti', 'EX', '4'),
('Aston Martin', 'DBS', '4'),
('Kia', 'Rio5', '4'),
('Pontiac', 'G8', '4'),
('Ferrari', '430 Scuderia', '4'),
('MINI', 'Clubman', '4'),
('MINI', 'Cooper Clubman', '4'),
('Buick', 'Enclave', '4'),
('Aptera', 'Typ-1', '4'),
('Maserati', 'GranTurismo', '4'),
('Smart', 'Fortwo', '4'),
('Scion', 'xD', '4'),
('Mercedes-Benz', 'SLK55 AMG', '4'),
('Mercedes-Benz', 'CL65 AMG', '4'),
('Audi', 'Q5', '4'),
('HUMMER', 'H3T', '4'),
('BMW', 'Z4 M Roadster', '4'),
('Chevrolet', 'Traverse', '4'),
('Volkswagen', 'CC', '4'),
('Volkswagen', 'Tiguan', '4'),
('Volkswagen', 'Routan', '4'),
('Volvo', 'XC60', '4'),
('Toyota', 'Venza', '4'),
('Pontiac', 'G3', '4'),
('Ferrari', 'California', '4'),
('Maybach', 'Landaulet', '4'),
('Dodge', 'Journey', '4'),
('Nissan', 'Cube', '4'),
('Nissan', 'GT-R', '4'),
('Nissan', '370Z', '4'),
('Ford', 'Flex', '4'),
('Bentley', 'Brooklands', '4'),
('Suzuki', 'Equator', '4'),
('Lincoln', 'MKS', '4'),
('Jaguar', 'XF', '4'),
('Aptera', '2e', '4'),
('Bugatti', 'Veyron', '4'),
('BMW', 'X5 M', '4'),
('BMW', 'X6 M', '4'),
('Honda', 'Accord Crosstour', '4');