INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Model T", "Luxuoso", "Hatch", "preto", "quis.tristique.ac@cursus.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Imperial", "Confortavel", "Perua/Van", "amarelo", "rutrum@turpisvitaepurus.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("2CV", "Luxuoso", "Perua/Van", "vermelho", "quis@facilisis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Minx Magnificent", "Confortavel", "Perua/Van", "amarelo", "tortor@interdumSedauctor.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Corvette", "Confortavel", "Hatch", "branco", "at.nisi@utodiovel.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Fleetwood", "Confortavel", "Hatch", "vermelho", "eros.turpis.non@magna.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Thunderbird", "Luxuoso", "Perua/Van", "verde", "nec@lacus.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("600", "Luxuoso", "Hatch", "prata", "feugiat@Praesent.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mini", "Basico", "Perua/Van", "prata", "nec.ante@nullaat.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Corvair", "Luxuoso", "Sedan", "branco", "neque.venenatis@rutrumjustoPraesent.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Fillmore", "Basico", "SUV", "preto", "ultrices.Vivamus@elitdictum.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Rockette", "Basico", "Hatch", "prata", "Praesent.interdum@adipiscingelit.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mini Cooper", "Luxuoso", "Hatch", "vermelho", "egestas.Aliquam@aliquet.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Avanti", "Confortavel", "Perua/Van", "amarelo", "dolor@aliquetmagna.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Tempest", "Basico", "SUV", "prata", "rhoncus.id@Etiambibendum.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Grand Prix", "Confortavel", "Hatch", "azul", "blandit@ridic(ulusmusAenean.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Special", "Luxuoso", "SUV", "preto", "est.Nunc.laoreet@acmi.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mini Cooper S", "Confortavel", "Hatch", "preto", "sit@arcu.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("E-Series", "Basico", "SUV", "azul", "eget@lobortis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Corvair 500", "Basico", "SUV", "vermelho", "lacinia.vitae.sodales@ametnulla.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mustang", "Basico", "Sedan", "branco", "Nunc.ullamcorper.velit@velconvallis.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Galaxie", "Luxuoso", "Sedan", "branco", "Aliquam.gravida.mauris@ipsumprimis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("LeMans", "Basico", "Sedan", "prata", "habitant.morbi@eu.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Bonneville", "Basico", "Perua/Van", "prata", "sodales.elit@etnetus.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Fairlane", "Confortavel", "Sedan", "amarelo", "Nullam.velit.dui@elitEtiamlaoreet.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Beetle", "Confortavel", "SUV", "amarelo", "lectus@est.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Falcon", "Basico", "SUV", "branco", "natoque.penatibus@iaculisaliquet.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Interceptor", "Confortavel", "Hatch", "verde", "dictum.sapien.Aenean@InloremDonec.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Toronado", "Luxuoso", "Sedan", "preto", "et.magnis@congueelit.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Firebird", "Confortavel", "SUV", "azul", "pede.Cras.vulputate@euismodurna.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Camaro", "Luxuoso", "Sedan", "verde", "aptent.taciti@velmaurisInteger.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Bel Air", "Basico", "Sedan", "verde", "mattis.Integer.eu@pellentesqueeget.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Country", "Luxuoso", "Sedan", "vermelho", "augue.scelerisque.mollis@id.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Cougar", "Basico", "Hatch", "vermelho", "libero.mauris.aliquam@magnisdis.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Charger", "Basico", "Sedan", "branco", "fermentum.vel@semutcursus.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("GT350", "Confortavel", "Perua/Van", "verde", "magna@eratvolutpatNulla.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Torino", "Basico", "Sedan", "preto", "malesuada@lectus.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("914", "Basico", "Hatch", "branco", "et@pedesagittis.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Vega", "Basico", "Hatch", "verde", "Duis.gravida.Praesent@tincidunt.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("SM", "Confortavel", "SUV", "prata", "nec.leo.Morbi@lobortisultrices.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Monte Carlo", "Basico", "Hatch", "preto", "eget.dictum@neque.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("CX", "Luxuoso", "Sedan", "amarelo", "odio@auctornunc.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Monza", "Basico", "Sedan", "prata", "mauris.sapien@atlibero.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Golf", "Basico", "Perua/Van", "azul", "vulputate.posuere@tellus.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Celica", "Confortavel", "Sedan", "branco", "vulputate.nisi@Suspendissenonleo.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Caprice", "Luxuoso", "Perua/Van", "prata", "elit.pellentesque@ametnullaDonec.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("W123", "Basico", "Perua/Van", "vermelho", "tellus.lorem@eget.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("MGB", "Basico", "SUV", "branco", "dolor.sit@orcilacusvestibulum.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Omni", "Basico", "Sedan", "amarelo", "non.magna@montesnascetur.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("280ZX", "Basico", "SUV", "verde", "non@arcuimperdiet.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("LUV", "Luxuoso", "Perua/Van", "amarelo", "Phasellus.in.felis@vulputate.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Riviera", "Confortavel", "Sedan", "amarelo", "condimentum.eget@Integervulputaterisus.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Citation", "Basico", "Perua/Van", "vermelho", "Cras@egetvolutpatornare.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Civic", "Confortavel", "SUV", "preto", "posuere.cubilia.Curae@vitaealiquam.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Aries", "Confortavel", "Hatch", "preto", "mi.eleifend@Donecnonjusto.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("W126", "Luxuoso", "Sedan", "branco", "Cum.sociis.natoque@et.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("6000", "Luxuoso", "SUV", "branco", "venenatis.lacus@justosit.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Sunbird", "Luxuoso", "Perua/Van", "prata", "leo.Cras.vehicula@non.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Accord", "Confortavel", "Sedan", "prata", "Nunc@feugiat.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Alliance", "Basico", "Hatch", "vermelho", "orci.luctus@commodo.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("626", "Luxuoso", "Sedan", "amarelo", "Duis.mi@Nam.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("RX-7", "Confortavel", "SUV", "amarelo", "Ut@magnaaneque.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("944", "Basico", "SUV", "vermelho", "enim.Suspendisse@orci.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("1000", "Luxuoso", "Sedan", "branco", "ac.tellus@imperdietdictum.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Parisienne", "Basico", "Hatch", "prata", "aliquet.vel@magnaPhasellus.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Fiero", "Luxuoso", "SUV", "azul", "porttitor.eros.nec@sitamet.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Firefly", "Basico", "Perua/Van", "preto", "eu@Sedpharetra.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Bronco II", "Luxuoso", "Perua/Van", "verde", "Phasellus.nulla@ipsum.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Laser", "Basico", "SUV", "amarelo", "fringilla@nibhsit.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("EXP", "Confortavel", "Hatch", "vermelho", "Nulla.semper@duiSuspendisse.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Ranger", "Confortavel", "Perua/Van", "amarelo", "elit@consectetuereuismodest.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Escort", "Luxuoso", "SUV", "amarelo", "in.consectetuer.ipsum@ametdapibusid.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Tempo", "Confortavel", "Sedan", "amarelo", "justo.faucibus.lectus@vitae.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("LTD", "Luxuoso", "SUV", "amarelo", "faucibus.Morbi.vehicula@sitametfaucibus.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("F250", "Luxuoso", "SUV", "preto", "tincidunt@facilisisnon.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("F150", "Luxuoso", "Perua/Van", "azul", "Aenean@In.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("E250", "Confortavel", "Sedan", "vermelho", "netus.et@justo.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("LTD Crown Victoria", "Luxuoso", "Perua/Van", "branco", "ullamcorper.velit.in@mollisIntegertincidunt.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Bronco", "Basico", "Sedan", "verde", "vel.faucibus@Fuscealiquamenim.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("E150", "Luxuoso", "SUV", "prata", "augue.ut.lacus@laoreetlectusquis.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Galant", "Confortavel", "Hatch", "vermelho", "eget.massa.Suspendisse@diamdictumsapien.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mirage", "Basico", "SUV", "prata", "nibh.Aliquam.ornare@magnisdis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Starion", "Luxuoso", "SUV", "vermelho", "sit@mifelisadipiscing.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Pajero", "Luxuoso", "Hatch", "verde", "at.lacus@justo.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Cordia", "Basico", "Hatch", "preto", "Sed@dapibus.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Tredia", "Luxuoso", "Hatch", "azul", "tortor.dictum@lorem.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Brat", "Luxuoso", "Sedan", "branco", "amet.ornare.lectus@etmagnis.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("S-Class", "Luxuoso", "Perua/Van", "azul", "Cras.dictum.ultricies@sem.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("E-Class", "Confortavel", "Perua/Van", "verde", "amet@magnamalesuada.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("W201", "Confortavel", "Hatch", "branco", "semper@accumsanlaoreet.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("SL-Class", "Confortavel", "SUV", "branco", "pede@egetnisi.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Topaz", "Confortavel", "Perua/Van", "branco", "Phasellus.at.augue@gravida.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Grand Marquis", "Confortavel", "Hatch", "branco", "aliquet@posuere.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Lynx", "Luxuoso", "Sedan", "branco", "Integer@purusNullam.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Capri", "Luxuoso", "Sedan", "preto", "rutrum.justo.Praesent@nisiAeneaneget.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Marquis", "Confortavel", "Hatch", "prata", "tellus.id@odio.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Esprit Turbo", "Luxuoso", "Sedan", "verde", "est@mattis.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Jetta", "Luxuoso", "Sedan", "prata", "lobortis@sagittisaugueeu.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Vanagon", "Basico", "Hatch", "amarelo", "Donec.luctus.aliquet@mus.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Scirocco", "Confortavel", "Hatch", "verde", "tellus@metusInnec.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Quantum", "Confortavel", "Sedan", "verde", "lobortis.quam@vulputate.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Electra", "Confortavel", "Perua/Van", "branco", "per.conubia@euerosNam.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Century", "Confortavel", "Perua/Van", "amarelo", "egestas@purusNullamscelerisque.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Skyhawk", "Luxuoso", "Sedan", "preto", "magna.Lorem@variusNam.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Town Car", "Confortavel", "SUV", "vermelho", "Phasellus.libero.mauris@sit.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Continental", "Confortavel", "Hatch", "vermelho", "vel.pede.blandit@augue.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mark VII", "Basico", "Perua/Van", "vermelho", "Aliquam@nisi.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Quattroporte", "Luxuoso", "Sedan", "amarelo", "luctus.lobortis.Class@lectusquismassa.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Biturbo", "Luxuoso", "SUV", "azul", "cursus.a.enim@nunc.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("900", "Basico", "SUV", "prata", "Lorem.ipsum@maurisblanditmattis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("5000S", "Basico", "SUV", "preto", "interdum.Sed@tortorNunccommodo.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("CR-X", "Confortavel", "Hatch", "verde", "nec.diam@dignissim.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Prelude", "Basico", "Sedan", "preto", "Nam.ac.nulla@sapienCras.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Daytona", "Confortavel", "Hatch", "prata", "aliquet@elitelitfermentum.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("SJ 410", "Confortavel", "Sedan", "amarelo", "at@ullamcorper.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("GLC", "Luxuoso", "Perua/Van", "amarelo", "libero.Integer@ornareIn.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Somerset", "Confortavel", "Perua/Van", "prata", "dui.in.sodales@placerat.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("LeSabre", "Basico", "SUV", "branco", "urna.Vivamus.molestie@Maurisquisturpis.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Regal", "Luxuoso", "Sedan", "verde", "aliquet@enimNunc.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Skylark", "Basico", "Sedan", "prata", "Ut.semper.pretium@ac.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("F-Series", "Basico", "Perua/Van", "branco", "dignissim.tempor.arcu@maurisrhoncusid.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Truck", "Basico", "Sedan", "branco", "arcu.Morbi.sit@pharetraQuisque.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Chariot", "Basico", "Perua/Van", "preto", "sem@aaliquetvel.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Passat", "Basico", "Hatch", "amarelo", "aliquet.magna@tortoratrisus.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Type 2", "Luxuoso", "Perua/Van", "prata", "nisi.Mauris.nulla@ac.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("4000s", "Luxuoso", "Perua/Van", "branco", "tellus.Suspendisse.sed@aliquetProinvelit.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Quattro", "Luxuoso", "Sedan", "amarelo", "augue.Sed.molestie@facilisiSedneque.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Coupe GT", "Luxuoso", "SUV", "preto", "semper.cursus@Praesent.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Countach", "Confortavel", "Hatch", "branco", "pharetra.ut@Integertincidunt.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Familia", "Basico", "SUV", "amarelo", "Aenean.eget.metus@aliquetlobortisnisi.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("B2000", "Luxuoso", "Sedan", "preto", "erat@turpisvitae.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Grand Am", "Basico", "Hatch", "prata", "Integer@utpharetrased.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("XT", "Basico", "Hatch", "vermelho", "pharetra.felis@feugiatnon.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Leone", "Confortavel", "Hatch", "amarelo", "ullamcorper.Duis@in.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("XR4Ti", "Confortavel", "SUV", "amarelo", "in@dui.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("911", "Luxuoso", "Sedan", "prata", "amet.dapibus.id@pedemalesuadavel.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("928", "Basico", "Sedan", "preto", "lacus.varius.et@eget.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Cultus", "Basico", "Perua/Van", "azul", "mi.lorem@nec.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("SJ", "Basico", "Sedan", "verde", "sed.turpis.nec@ligulaAliquamerat.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("MR2", "Confortavel", "Perua/Van", "verde", "elementum.sem.vitae@Sed.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Esprit", "Confortavel", "Hatch", "verde", "lobortis.mauris.Suspendisse@adipiscing.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Caravan", "Confortavel", "Hatch", "preto", "volutpat.ornare.facilisis@egestas.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Taurus", "Confortavel", "SUV", "prata", "Ut.tincidunt@atpretium.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Aerostar", "Basico", "Sedan", "vermelho", "Aliquam@eueuismodac.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Courier", "Luxuoso", "Perua/Van", "prata", "elit@mollisvitaeposuere.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Mighty Max", "Luxuoso", "SUV", "prata", "mauris.ut@mitemporlorem.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Precis", "Confortavel", "Sedan", "prata", "at.pede.Cras@odiosagittissemper.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Safari", "Confortavel", "Hatch", "azul", "ac@temporlorem.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Gemini", "Confortavel", "Perua/Van", "vermelho", "arcu.Sed@Curae.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Firebird Trans Am", "Confortavel", "Hatch", "verde", "magnis.dis.parturient@euultrices.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("5000CS Quattro", "Basico", "Hatch", "vermelho", "Duis.mi@sagittisplacerat.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("4000s Quattro", "Basico", "SUV", "verde", "arcu.iaculis.enim@estac.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("4000CS Quattro", "Basico", "SUV", "verde", "ac@sedtortorInteger.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Sable", "Confortavel", "Hatch", "prata", "Nunc.mauris.Morbi@atrisus.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("B-Series", "Confortavel", "SUV", "preto", "fermentum.vel.mauris@lectus.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("9000", "Basico", "SUV", "azul", "nunc@aliquetodioEtiam.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Range Rover", "Luxuoso", "Hatch", "amarelo", "accumsan@lectusquis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("4000", "Confortavel", "Perua/Van", "verde", "Quisque@mauris.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("5000CS", "Basico", "SUV", "vermelho", "varius.et.euismod@eleifendnon.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("929", "Basico", "Hatch", "vermelho", "urna.nec.luctus@enimcondimentumeget.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("B2600", "Confortavel", "Hatch", "branco", "interdum.feugiat.Sed@turpisNulla.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Fox", "Luxuoso", "Perua/Van", "vermelho", "ligula@eratinconsectetuer.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Swift", "Confortavel", "Perua/Van", "preto", "erat.nonummy.ultricies@sem.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Justy", "Confortavel", "Hatch", "branco", "ipsum@necleo.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("924 S", "Basico", "Perua/Van", "amarelo", "aliquet.odio@placerategetvenenatis.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Chevette", "Basico", "SUV", "prata", "mus@Nunc.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("L300", "Luxuoso", "Sedan", "branco", "eu.tempor@mauris.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Legend", "Basico", "Hatch", "branco", "sociis.natoque.penatibus@Integeraliquamadipiscing.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Integra", "Basico", "Hatch", "branco", "est.mauris.rhoncus@acurna.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("924", "Confortavel", "SUV", "amarelo", "est@Quisquefringillaeuismod.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Turbo Firefly", "Luxuoso", "Hatch", "azul", "dignissim.tempor@Phaselluselitpede.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Tracer", "Basico", "SUV", "azul", "nisi.a@laciniaat.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Reatta", "Luxuoso", "Sedan", "verde", "In@Nunc.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Festiva", "Luxuoso", "Hatch", "amarelo", "penatibus.et@sitamet.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("MX-6", "Luxuoso", "SUV", "amarelo", "enim@fermentumconvallisligula.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("90", "Confortavel", "Hatch", "verde", "id.mollis@gravidanon.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("80/90", "Luxuoso", "Sedan", "amarelo", "lacinia@dolor.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Estate", "Luxuoso", "SUV", "azul", "auctor@molestiesodales.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Probe", "Basico", "Hatch", "verde", "tempus.non.lacinia@tinciduntduiaugue.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("MPV", "Confortavel", "Perua/Van", "vermelho", "nisi.a@diam.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Sigma", "Basico", "Perua/Van", "preto", "eu@maurisa.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Eclipse", "Basico", "Perua/Van", "prata", "Pellentesque.ut@sociosquadlitora.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Legacy", "Basico", "SUV", "branco", "12345");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Sidekick", "Basico", "Sedan", "branco", "et@natoquepenatibuset.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("ES", "Luxuoso", "SUV", "azul", "scelerisque@Nulla.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("228", "Luxuoso", "SUV", "branco", "auctor.nunc.nulla@nec.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("430", "Luxuoso", "Hatch", "azul", "In@litora.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Spyder", "Confortavel", "SUV", "azul", "ligula@ornaresagittis.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Karif", "Confortavel", "Sedan", "preto", "nisi@auctornunc.co.uk");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("80", "Basico", "Sedan", "vermelho", "fringilla.cursus@tinciduntnequevitae.ca");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("100", "Basico", "Sedan", "azul", "semper.Nam@augueporttitorinterdum.net");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("200", "Basico", "Sedan", "preto", "primis.in.faucibus@at.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Truck Xtracab SR5", "Basico", "Perua/Van", "branco", "rutrum@sit.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("6 Series", "Basico", "Perua/Van", "amarelo", "adipiscing@montesnasceturridiculus.edu");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Coachbuilder", "Basico", "Hatch", "amarelo", "ipsum.Suspendisse.sagittis@velturpisAliquam.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Loyale", "Basico", "Sedan", "azul", "Cras.convallis.convallis@magnisdisparturient.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("MX-5", "Luxuoso", "SUV", "vermelho", "tempor.diam@semelitpharetra.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("V8", "Confortavel", "Perua/Van", "branco", "hendrerit.neque@mauris.org");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Coupe Quattro", "Luxuoso", "Hatch", "amarelo", "malesuada@duilectus.com");
INSERT INTO veiculo (modelo, conforto, categoria, cor, email_dono) VALUES ("Elan", "Confortavel", "Hatch", "verde", "egestas@duiFusce.ca");
